
Ext.ns("homework","homeworks.js");
Ext.define("homework.js.LoginUserInformation",{
	extend:'Ext.Panel',
	id:'infoMangerPanl',
	/*title:'个人信息修改',*/
	initComponent:function(){
		Ext.apply(this,{
			id:'infoMangerPanl',
			border:false,
			layout:'fit',
			bodyStyle:'padding 5px',
			items:[new Ext.form.FormPanel({
				id:'infoMangerForm',
				border:false,
				items:[{
					xtype:'fieldset',
					title:'个人信息修改',
					collapsible:true,
					autoHeight:true,
					width:600,
					autoScroll:false,
					layout:'column',
					items:[{
						columnWidth:0.6,
						layout:'form',
						border:false,
						items:[{
							xtype:'textfield',
							fieldLabel:'真实姓名',
							id:'realName',
							name:'realName',
							allowBlank:false,//不允许为空  
			                blankText:"真实姓名不能为空"
			              /*regex:/[/u4e00-/u9fa5]/,      
			                regexText:"只能输入中文!"*/
						},{
							xtype:'combo',
							store:homework.js.sex,
							displayField:'display',
							valueField:'value',
							triggerAction:'all',
							typeHead:true,
							editable:false,
							mode:'local',
							fieldLabel:'性别',
							id:'sex',
							name:'sex',
							allowBlank:false,//不允许为空  
			                blankText:"性别不能为空"
						},{
							xtype:'datefield',
							format:'Y-m-d',
							editable:false,
							fieldLabel:'出生日期',
							id:'birth',
							name:'birth',
							allowBlank:false,//不允许为空  
			                blankText:"日期不能为空"
						},{
							xtype:'combo',
							store:homework.js.education,
							displayField:'display',
							valueField:'value',
							triggerAction:'all',
							typeHead:true,
							mode:'local',
							editable:false,
							fieldLabel:'学历',
							id:'education',
							name:'education',
							allowBlank:false,//不允许为空  
			                blankText:"学历不能为空"
						},{
							xtype:'textfield',
							fieldLabel:'电话',
							id:'telephone',
							name:'telephone',
							allowBlank:false,//不允许为空  
			                blankText:"电话不能为空",
			                anchor:'90%'
						},{
							xtype:'textfield',
							fieldLabel:'邮箱',
							id:'email',
							vtype:"email",//email格式验证  
						    vtypeText:"不是有效的邮箱地址",
							name:'email',
							allowBlank:false,//不允许为空  
			                blankText:"不能为空"
						},{
							xtype:'textfield',
							fieldLabel:'身份证号',
							id:'card',
							name:'card',
							allowBlank:false,//不允许为空  
			                blankText:"身份证号不能为空"
						},{
							xtype:'combo',
							store:homework.js.hometown,
							displayField:'display',
							valueField:'value',
							triggerAction:'all',
							typeHead:true,
							mode:'local',
							editable:false,
							fieldLabel:'籍贯',
							id:'hometown',
							name:'hometown',
							allowBlank:false,//不允许为空  
			                blankText:"籍贯不能为空"
						},{
							xtype:'textfield',
							fieldLabel:'家庭地址',
							id:'address',
							name:'address',
							allowBlank:false,//不允许为空  
			                blankText:"地址不能为空"
						},{
							xtype:'textfield',
							fieldLabel:'个人简介',
							id:'introduction',
							name:'introduction',
							anchor:'90%'
						}],
						buttons:[{
							text:'保存修改',
							handler:function(){
							var realName =Ext.getCmp("realName").getValue();
							var sex =Ext.getCmp("sex").getValue();
							var birth =Ext.getCmp("birth").getValue();
							var education =Ext.getCmp("education").getValue();
							var telephone =Ext.getCmp("telephone").getValue();
							var email =Ext.getCmp("email").getValue();
							var card =Ext.getCmp("card").getValue();
							var address =Ext.getCmp("address").getValue();
							var hometown =Ext.getCmp("hometown").getValue();
							var introduction =Ext.getCmp("introduction").getValue();
								Ext.Ajax.request({
									url:path+'/userController/updataUserByid.do',
									method:'post',
									waitMsg:'请等待数据提交中',
									waitTitle:'修改',
									success:function(res){
										Ext.Msg.alert("操作结果","修改成功");
									},
									params:{
										id:loginUserId,
										realName:realName,
										sex:sex,
										birth:birth,
										education:education,
										telephone:telephone,
										email:email,
										card:card,
										address:address,
										hometown:hometown,
										introduction:introduction,
									}
								});
							}
						}]
					}]
				}]
			})]	
		});
		this.callParent(arguments);
		Ext.Ajax.request({
			url:path+'/userController/searchUserByid.do',
			method:'post',
			success:function(res){
				var result=Ext.JSON.decode(res.responseText);
				Ext.getCmp("realName").setValue(result[0].realName);
				Ext.getCmp("sex").setValue(result[0].sex);
				Ext.getCmp("birth").setValue(result[0].birth);
				Ext.getCmp("education").setValue(result[0].education);
				Ext.getCmp("telephone").setValue(result[0].telephone);
				Ext.getCmp("email").setValue(result[0].email);
				Ext.getCmp("card").setValue(result[0].card);
				Ext.getCmp("address").setValue(result[0].address);
				Ext.getCmp("hometown").setValue(result[0].hometown);
				Ext.getCmp("introduction").setValue(result[0].introduction);
			},
			params:{
				loginUserId:loginUserId
			}
		});
	}
});